# Generated by Django 4.1.10 on 2023-08-07 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='album',
            table='album',
        ),
        migrations.AlterModelTable(
            name='musician',
            table='musician',
        ),
    ]
